{% set name = "kanban-python" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kanban-python-{{ version }}.tar.gz
  sha256: ede47579afa7890c7444213984778fa59a524ee7fde7274eb9392c2a700df7a8

build:
  noarch: python
  entry_points:
    - kanban = kanban_python.app:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.7
    - importlib-metadata
    - rich >=13.7.0
    - platformdirs >=3,<4

test:
  imports:
    - kanban_python
  commands:
    - pip check
    - kanban --help
  requires:
    - pip

about:
  home: https://github.com/Zaloog/kanban-python
  summary: Terminal Kanban App written in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
