{% set name = "kanban-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6a683bf0b90acd52a4c79e68508f4f46f4c42ca9220f915e1b9c30eb7f0e9e7

build:
  noarch: python
  entry_points:
    - kanban = kanban_python.app:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs >=4.3.6
    - rich >=13.9.4

test:
  imports:
    - kanban_python
  commands:
    - pip check
    - kanban --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Zaloog/kanban-python
  summary: Terminal Kanban App written in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
